### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by funblaster22** [sasa95/pomodor#38]
Currently, no license means that the code is under default copyright protection and is owned exclusively by the creator meaning that no one may reproduce, distribute, or create derivative works from your work. If this is not intended, consider adding a license (see https://choosealicense.com/ for help choosing) which would allow other people to contribute and make the software better. If you would rather retain all rights to the software, maybe add a line to the README stating "(c) 2020 All Rights Reserved"

**Comment by sasa95** [comment]
Thank you very much for letting me know about this! 

The source code is now under MIT licence (0f74d9ecc12680287faf8a506486cc3e81dd406f), so feel free to do with it everything you want. :) 

I'd really love to see some contributions to this project in any way, since I don't have much free time to dedicate to new features.
